# Generated by Django 5.0.4 on 2024-04-29 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(db_column='ID', db_comment='チャット識別用ID', primary_key=True, serialize=False)),
                ('message', models.CharField(db_comment='メッセージ本文', max_length=255)),
                ('sendtime', models.DateTimeField(db_comment='メッセージ送信時間')),
                ('messagetype', models.IntegerField(db_column='messageType', db_comment='メッセージの種類')),
            ],
            options={
                'db_table': 'chat',
                'db_table_comment': 'チャット情報',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(db_column='ID', db_comment='チャットルーム識別用ID', primary_key=True, serialize=False)),
                ('roomname', models.CharField(db_comment='ルーム名', max_length=255)),
            ],
            options={
                'db_table': 'chatroom',
                'db_table_comment': 'チャットルーム',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fontsize', models.IntegerField(db_column='fontSize', db_comment='フォントサイズ')),
                ('font', models.CharField(db_comment='フォント', max_length=255)),
                ('noticeflg', models.IntegerField(db_column='noticeFlg', db_comment='通知フラグ')),
            ],
            options={
                'db_table': 'conf',
                'db_table_comment': '設定情報',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='ID', db_comment='ユーザ識別ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='ユーザー名', max_length=255)),
                ('loginid', models.CharField(db_column='loginID', db_comment='ログインID', max_length=255, unique=True)),
                ('passwd', models.CharField(db_comment='ログインパスワード', max_length=255)),
                ('lastlogin', models.DateTimeField(db_column='lastLogin', db_comment='最終ログイン')),
                ('createdate', models.DateTimeField(db_column='createDate', db_comment='アカウント作成日時')),
                ('iconimage', models.CharField(db_column='iconImage', db_comment='アイコン画像パス', max_length=255)),
                ('confid', models.IntegerField(db_column='ConfID', db_comment='設定情報ID')),
            ],
            options={
                'db_table': 'user',
                'db_table_comment': 'ユーザマスタ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roominfo',
            fields=[
                ('id', models.IntegerField(db_comment='ルーム情報ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'roominfo',
                'db_table_comment': 'チャットルーム情報',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('userid', models.OneToOneField(db_column='userId', db_comment='ユーザーID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='react_app.user')),
                ('satisfieddate', models.DateTimeField(db_column='satisfiedDate', db_comment='フレンド成立日時')),
            ],
            options={
                'db_table': 'friend',
                'db_table_comment': 'フレンド情報',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Friendrequest',
            fields=[
                ('applicantid', models.OneToOneField(db_column='applicantId', db_comment='申請者ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='react_app.user')),
                ('applicantdate', models.DateTimeField(blank=True, db_column='applicantDate', db_comment='申請日時', null=True)),
            ],
            options={
                'db_table': 'friendrequest',
                'db_table_comment': 'フレンド申請',
                'managed': False,
            },
        ),
    ]
