# Generated by Django 5.0.4 on 2024-05-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(db_column='ID', db_comment='チャット識別用ID', primary_key=True, serialize=False)),
                ('message', models.CharField(db_comment='メッセージ本文', max_length=255)),
                ('sendtime', models.DateTimeField(db_comment='メッセージ送信時間')),
                ('messagetype', models.IntegerField(db_column='messageType', db_comment='メッセージの種類')),
            ],
            options={
                'db_table': 'chat',
                'db_table_comment': 'チャット情報',
                'managed': False,
            },
        ),
    ]
